Removed setting cwd
With `cwd` being set I was constantly getting the following "RuntimeError: Environment went away" error.
```
Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/lektor/admin/utils.py", line 18, in generate
    for event in chain(f(*args, **kwargs), (None,)):
  File "/usr/local/lib/python3.7/site-packages/lektor/admin/modules/api.py", line 315, in generator
    for event in event_iter:
  File "/usr/local/lib/python3.7/site-packages/lektor_git_src_publisher.py", line 72, in publish
    for line in self._git(["fetch", "--progress"]).output:
  File "/usr/local/lib/python3.7/site-packages/lektor_git_src_publisher.py", line 17, in _git
    root_path = self._plugin.env.root_path
  File "/usr/local/lib/python3.7/site-packages/lektor/pluginsystem.py", line 40, in env
    raise RuntimeError('Environment went away')
RuntimeError: Environment went away
```